# Generated by Django 3.0.8 on 2020-07-04 19:09

from django.db import migrations


def fill_data(apps, schema_editor):
    Poll = apps.get_model('polls', 'Poll')
    Question = apps.get_model('polls', 'Question')
    AnswerOption = apps.get_model('polls', 'AnswerOption')
    poll = Poll.objects.create(header='Tabs vs Spaces')
    question = Question.objects.create(text='Do you use tabs or spaces for indentation?', poll=poll)
    AnswerOption.objects.create(question=question, text='Tabs')
    AnswerOption.objects.create(question=question, text='Spaces')


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_data, reverse_code=migrations.RunPython.noop)
    ]
